
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'user_status','用户状态','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','user_status','0','正常','admin','2018-08-10 15:02:44','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','user_status','1','程序锁定','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','user_status','2','人工锁定','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'id_kind','证件类型','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','id_kind','1','身份证','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'res_type','资源类型','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','res_type','1','菜单','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','res_type','2','按钮','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'lock_direction','锁定方向','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','lock_direction','1','锁定','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','lock_direction','2','解锁','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'kd_company','物流公司','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','EMS','邮政EMShhh','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','STO','申通快递','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','ZTO','中通快递','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','YTO','圆通快递','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','HTKY','汇通快递','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','SF','顺丰快递','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','TTKD','天天快递','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','ZJS','宅急送','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','BSHT','百世汇通','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','YDKD','韵达快递','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','DBKD','德邦快递','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','QFKD','全峰快递','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','GTKD','国通快递','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','TDHY','天地华宇','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','JJWL','佳吉物流','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','JJKD','快捷快递','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','YSKD','优速快递','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','kd_company','QTKD','其他','admin','2018-03-28 13:58:15','');
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'user_kind','针对人群','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','user_kind','C','C端用户','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','user_kind','B','代理','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','user_kind','P','平台所有用户','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'material_type','素材类型','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','material_type','0','产品素材','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','material_type','1','培训素材','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'inner_status','内购产品状态','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','inner_status','1','待上架','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','inner_status','2','已上架','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','inner_status','3','已下架','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'product_status','产品状态','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','product_status','1','待上架','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','product_status','2','已上架','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','product_status','3','已下架','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'award','奖励','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','award','0','推荐奖励','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','award','1','出货奖励','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','award','2','介绍奖励','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'charge_status','充值订单状态','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','charge_status','1','代支付','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','charge_status','2','支付失败','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','charge_status','3','支付成功','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','charge_status','4','待审核','admin','2018-04-19 09:35:53',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','charge_status','5','审核未通过','admin','2018-04-19 09:35:53',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','charge_status','6','审核通过','admin','2018-04-19 09:35:53',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'inner_order_status','内购产品订单状态','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','inner_order_status','0','待支付','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','inner_order_status','1','已支付待发货','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','inner_order_status','2','已支付待发货','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','inner_order_status','3','待收货','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','inner_order_status','4','已收货','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','inner_order_status','5','申请取消','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','inner_order_status','6','已取消','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'jour_status','流水状态','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','jour_status','1','待对账','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','jour_status','3','已对账且账已平','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','jour_status','4','帐不平待调账审批','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'channel_type','渠道类型','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','channel_type','90','线下支付','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','channel_type','35','微信充值','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'biz_type','业务类型','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','biz_type','11','取现','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','biz_type','XXFK','体现回录','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','biz_type','AJ_CZ','充值','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','biz_type','AJ_KK','扣款','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','biz_type','AJ_MKCZ','门槛充值','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','biz_type','AJ_GMNP','购买内购商品','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','biz_type','AJ_GMYC','购买云仓','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','biz_type','AJ_CELR','差额利润','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','biz_type','AJ_TJJL','推荐奖励','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','biz_type','AJ_CHJL','出货奖励','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','jour_status','5','已对账且账不平','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','jour_status','6','无需对账','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'withdraw_status','取现状态','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','withdraw_status','1','待审批','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','withdraw_status','2','审批不通过','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','withdraw_status','3','审批通过待支付','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','withdraw_status','4','支付失败','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','withdraw_status','5','支付成功','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0','','out_order_status','提货订单状态','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','out_order_status','0','待支付','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','out_order_status','1','已支付待审核','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','out_order_status','2','已审单待发货','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','out_order_status','3','待收货','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','out_order_status','4','已收货','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','out_order_status','5','申请取消','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','out_order_status','6','已取消','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'agent_status','代理状态','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_status','0','有意向','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` (`type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_status','1','已忽略','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_status','2','待填写授权资料','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_status','3','补充授权资料','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_status','4','待上级授权','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_status','5','待公司授权','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_status','6','已授权','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_status','7','未授权','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_status','8','退出待上级审核','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_status','9','退出待公司审核','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_status','10','升级待上级审核','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_status','11','升级待公司审核','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'agent_type','代理轨迹类型','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_type','0','意向分配','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_type','1','授权','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_type','2','升级','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'out_order_type','订单类型','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','out_order_type','0','普通单','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','out_order_type','1','升级单','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','out_order_type','2','授权单','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','out_order_type','3','订单类型','admin','2018-04-19 09:35:53',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','out_order_type','4','C端订单类型','admin','2018-04-19 09:35:53',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','biz_type','AJ_JSJL','介绍奖励','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'currency','币种','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','currency','TX_CNY','可提现账户','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','currency','TC_CNY','云仓账户','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','currency','MK_CNY','门槛账户','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'change_product_status','置换单','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','change_product_status','0','申请换货','admin','2018-03-28 13:58:15',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','change_product_status','1','申请通过','admin','2018-04-12 10:22:52',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','change_product_status','2','申请未通过','admin','2018-04-12 10:22:55',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','biz_type','AJ_GMCP','购买产品','admin','2018-04-12 10:22:55',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'product_log_type','产品库存记录类型','admin','2018-04-12 10:22:55',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','product_log_type','0','出库','admin','2018-04-12 10:22:55',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','product_log_type','1','入库','admin','2018-04-12 10:22:55',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','product_log_type','2','代理下单','admin','2018-04-12 10:22:55',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','product_log_type','3','代理换货','admin','2018-04-12 10:22:55',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'agnecy_log_type','代理轨迹类型','admin','2018-04-12 10:22:55',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agnecy_log_type','0','意向分配','admin','2018-04-12 10:22:55',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agnecy_log_type','1','授权','admin','2018-04-12 10:22:55',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agnecy_log_type','2','升级','admin','2018-04-12 10:22:55',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agnecy_log_type','3','退出','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'account_status','账户状态','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','account_status','0','正常','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','account_status','1','程序锁定','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','account_status','2','人工锁定','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'address_type','地址类型','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','address_type','1','用户地址','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'banner_status','banner图状态','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','banner_status','0','待发布','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','banner_status','1','已发布','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','banner_status','2','已撤下','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'sq_status','授权单状态','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','sq_status','3','补充授权资料','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','sq_status','4','待上级审核授权','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','sq_status','5','授权待公司审核','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','sq_status','6','已授权','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','sq_status','7','授权未通过','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','sq_status','8','申请退出待上级审核','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','sq_status','9','申请退出待公司审核','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'yx_status','意向单状态','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','yx_status','0','有意愿','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','yx_status','1','已忽略','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','yx_status','2','已分配','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','yx_status','3','已接受','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'sj_status','升级单状态','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','sj_status','10','上级审核升级','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','sj_status','11','公司审核升级','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','sj_status','12','已升级','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','sj_status','13','升级未通过','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'agent_log_status','代理轨迹状态','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','0','有意向','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','1','已分配','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','2','接受意向','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','3','已忽略','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','4','待填写授权资料','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','5','补充授权资料','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','6','待上级授权','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','7','待公司授权','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','8','已授权','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','9','未授权','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','10','退出待上级审核','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','11','退出待公司审核','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','12','升级待上级审核','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','13','升级待公司审核','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','14','已升级','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','agent_log_status','15','升级未通过','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'in_order_status','云仓订单状态','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','in_order_status','0','待支付','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','in_order_status','1','已收货','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','in_order_status','2','申请取消','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','in_order_status','3','已取消','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','in_order_status','4','支付失败','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('0',NULL,'pro_code_status','箱码状态','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','pro_code_status','0','待下载','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','pro_code_status','0','待下载','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','pro_code_status','0','待下载','admin','2018-04-13 16:49:02',NULL);
insert into `tsys_dict` ( `type`, `parent_key`, `dkey`, `dvalue`, `updater`, `update_datetime`, `remark`) values('1','pro_code_status','0','待下载','admin','2018-04-13 16:49:02',NULL);
